# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
  dev.kint_extension:
    class: "AppBundle\\Twig\\KintExtension"
    public: true
    tags:
      - { name: twig.extension }

  sticky.locale:
    class: "AppBundle\\EventSubscriber\\LocaleSubscriber"
    arguments: ['%kernel.default_locale%']
    tags: 
      - {name: 'kernel.event_subscriber'}
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
